steps:
  - label: ":env: Getting repo"
    command: |
      rm -rf test
      mkdir test
      cd test
      wget https://github.com/StepanBoiko/getbooked/archive/refs/heads/master.zip
      unzip master.zip
      cd getbooked-master/app

  - label: ":ruby: Install Dependencies"
    command: |
      ls -la
      cd test/getbooked-master/app
      # bundle install

  - label: ":rails: Database Setup"
    command: |
      rails db:create
      rails db:migrate

  - wait

  - label: ":test: Run Tests"
    command: |
      rails test

  - wait

  - label: ":deploy: Deploy to Production"
    command: |
      # Add deployment commands here
      # For example:
      # - Copy files to the production server
      # - Run migrations on the production database
      # - Restart the application server

# You can define more steps for deployment to different environments (staging, etc.)
