# .buildkite/pipeline.yml

steps:
  - label: ":ruby: Install Dependencies"
    commands: 
      - ls -la
      - cd app
      - sudo yum install -y nodejs
      - sudo yum groupinstall "Development Tools" -y
      - sudo yum install openssl-devel libyaml-devel libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel -y
      - sudo yum install -y gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison sqlite-devel -y
      - command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
      - command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
      - \curl -sSL https://get.rvm.io | bash -s stable
      - gem install rails --no-document
      - rails -v
      - ruby -v
      - bundle install
    

  - label: ":ruby: Database Setup"
    commands: 
      - rails db:create 
      - rails db:migrate
    

  - label: ":rails: Run Tests"
    command: "rails test"
    
