# .buildkite/pipeline.yml

steps:
  - label: ":ruby: Install Dependencies"
    commands: 
      - ls -la
      - cd app
      - bundle install
    

  - label: ":ruby: Database Setup"
    commands: 
      - rails db:create 
      - rails db:migrate
    

  - label: ":rails: Run Tests"
    command: "rails test"
    
