steps:
  - label: ":env: Getting repo"
    commands:
      - ls -la
      - sudo yum install -y nodejs
      - sudo yum groupinstall "Development Tools" -y
      - sudo yum install openssl-devel libyaml-devel libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel -y
      - sudo yum install -y gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison sqlite-devel -y
      - command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
      - command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
      - \curl -sSL https://get.rvm.io | bash -s stable
      - rvm install 3.2.2
      - gem install rails --no-document
      - cd app
      



  

#   - label: ":rails: Database Setup"
#     command: |
#       rails db:create
#       rails db:migrate

#   - wait

#   - label: ":test: Run Tests"
#     command: |
#       rails test

#   - wait

#   - label: ":deploy: Deploy to Production"
#     command: |
#       # Add deployment commands here
#       # For example:
#       # - Copy files to the production server
#       # - Run migrations on the production database
#       # - Restart the application server

# # You can define more steps for deployment to different environments (staging, etc.)
