# .buildkite/pipeline.yml

steps:
  - label: ":ruby: Install Dependencies"
    commands: 
      - whoami 
      - cd /var/lib/buildkite-agent/builds/ip-172-31-23-159-ec2-internal-1/company-1/getbookedcicd/app
      - bundle install

  - wait

  - label: ":ruby: Database Setup"
    commands: 
      - rails db:create 
      - rails db:migrate    

  - wait

  - label: ":rails: Run Tests"
    commands: 
      - cd /var/lib/buildkite-agent/builds/ip-172-31-23-159-ec2-internal-1/company-1/getbookedcicd/app
      - rails test

  # - wait

  # - label: ":rails: Deploy"
  #     commands: 
  #       - cd /var/lib/buildkite-agent/builds/ip-172-31-23-159-ec2-internal-1/company-1/getbookedcicd/app/scripts
  #       - bash deploy_staging.sh

    
# cd /var/lib/buildkite-agent/builds/ip-172-31-39-37-ec2-internal-1/company-1/getbookedcicd/