steps:
  - label: ":rails: Install Dependencies"
    command: "bundle install"
    agents:
      queue: "rails"

  - label: ":rails: Database Setup"
    command: "bin/rails db:create db:schema:load"
    agents:
      queue: "rails"

  - label: ":rails: Run Tests"
    command: "bin/rails test"
    agents:
      queue: "rails"
      
  - label: ":rails: Deploy"
    command: "bin/deploy"  # Replace with your deployment script
    branches: "main"
    agents:
      queue: "deploy"