# .buildkite/pipeline.yml

steps:
  - label: ":ruby: Install Dependencies"
    commands: 
      # - ls -la
      - whoami
      # - sudo chmod +x switchuser.sh
      # - ./switchuser.sh
      # - cd /var/lib/buildkite-agent/builds/ip-172-31-43-15-ec2-internal-1/company-1/getbookedcicd/app
      # - sudo yum install -y nodejs
      # - sudo yum groupinstall "Development Tools" -y
      # - sudo yum install openssl-devel libyaml-devel libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel -y
      # - sudo yum install -y gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison sqlite-devel -y
      # - command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
      # - command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
      # - \curl -sSL https://get.rvm.io | bash -s stable
      # - ruby -v
      # - sudo gem install rails --no-document
      # - rails -v
      # - bundle install
    

  - label: ":ruby: Database Setup"
    commands: 
      - cd /var/lib/buildkite-agent/builds/ip-172-31-43-15-ec2-internal-1/company-1/getbookedcicd/app
      - bundle install
      - rails db:create 
      - rails db:migrate
    

  - label: ":rails: Run Tests"
    commands: 
      - cd /var/lib/buildkite-agent/builds/ip-172-31-43-15-ec2-internal-1/company-1/getbookedcicd/app
      - rails test


    
# cd /var/lib/buildkite-agent/builds/ip-172-31-39-37-ec2-internal-1/company-1/getbookedcicd/