# .buildkite/pipeline.yml

steps:
  - label: ":ruby: Install Dependencies"
    commands: 
      - ls -la
      - cd app
      - bundle install --jobs=6
    agents:
      queue: "rails"

  - label: ":ruby: Database Setup"
    commands: 
      - rails db:create 
      - rails db:migrate
    agents:
      queue: "rails"

  - label: ":rails: Run Tests"
    command: "rails test"
    agents:
      queue: "rails"
